# Generated by Django 5.0.6 on 2024-06-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_entrenador_horas_entrenadas_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrenador',
            new_name='Coach',
        ),
        migrations.RenameModel(
            old_name='Jugador',
            new_name='Player',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='coach',
            table='accounts_coach',
        ),
        migrations.AlterModelTable(
            name='player',
            table='accounts_player',
        ),
    ]
