# Generated by Django 5.0.6 on 2024-06-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_entrenador_coach_rename_jugador_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('jugador', 'Player'), ('entrenador', 'Coach')], max_length=20),
        ),
    ]
