# Generated by Django 5.0.6 on 2024-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalweb', '0005_contact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('introduction', models.TextField()),
                ('title_image', models.ImageField(upload_to='images/')),
                ('character_image', models.ImageField(upload_to='images/')),
                ('background_image', models.ImageField(upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
