# Generated by Django 5.0.6 on 2024-06-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalweb', '0006_characterrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='video1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='video2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='video3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
