# Generated by Django 5.0.6 on 2024-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalweb', '0008_alter_personaje_video1_alter_personaje_video2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterrequest',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='characterrequest',
            name='video1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='characterrequest',
            name='video2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='characterrequest',
            name='video3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='background_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='character_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='title_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
