# Generated by Django 5.0.6 on 2024-06-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalweb', '0009_rename_create_at_characterrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterrequest',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='background_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='character_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='title_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='video1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='video2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='video3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='video1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='video2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='video3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
