# Generated by Django 5.0.6 on 2024-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalweb', '0010_rename_created_at_characterrequest_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterrequest',
            name='video1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='video2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='characterrequest',
            name='video3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='video1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='video2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='video3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
